model_folder: "exps/weights/"
initial_model_path: "allenai/scibert_scivocab_uncased"
log_folder: "logs"
log_file_name: "train.log"
paper_database_path: "dataset/acl_200/papers.json"
train_corpus_path: "dataset/acl_200/train.json"
test_corpus_path: "dataset/acl_200/test.json"
val_corpus_path: "dataset/acl_200/val.json"
context_database_path: "dataset/acl_200/contexts_200.json"
num_epochs: 5
n_device: 1
n_document: 10
n_query_per_batch: 1
gpu_list: null
restore_old_checkpoint: 1
initial_learning_rate: 1e-5
l2_weight: 0.01
num_workers: 8
save_every: 2000
print_every: 1000
validate_every: 2000
num_validation_iterations: 1000
max_input_length: 512
base_margin: 0.1
rerank_top_K: 2000
n_training_examples_wt_prefetched_ids_for_reranking: 10000
n_valid_examples_wt_prefetched_ids_for_reranking: 1000
max_n_positive: 1
train_corpus_sampling_ratio: 1.0
val_corpus_sampling_ratio: 1.0
max_num_checkpoints: 2
num_negs: 50